import { afterAll, describe, expect, test } from 'vitest';
import { randomBytes } from 'node:crypto';
import { Client, escapeIdentifier } from 'pg';
import { createOwnedDatabase } from '../src/database.js';
import { captureFixtureIdentity, FixtureIdentityError } from '../src/fixture-identity.js';
import type { OwnedDatabase } from '../src/types.js';
import { testDatabaseUrl } from './helpers/postgres.js';
const adminUrl = testDatabaseUrl();
const integration = describe;
const databases: OwnedDatabase[] = [];
async function database(sql = '') {
  const owned = await createOwnedDatabase(adminUrl!); databases.push(owned);
  if (sql) await owned.db.query(sql);
  return owned;
}
const fixture = `
  CREATE SCHEMA app;
  CREATE TYPE app.mood AS ENUM ('calm', 'busy');
  CREATE DOMAIN app.code AS text CHECK (length(VALUE) > 0);
  CREATE TYPE app.detail AS (label text, numbers integer[]);
  CREATE TABLE app.items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code app.code NOT NULL, mood app.mood, amount numeric(12,3), payload bytea,
    nested jsonb, tags integer[], detail app.detail, moment timestamptz
  );
  CREATE INDEX items_mood ON app.items(mood);
  CREATE FUNCTION app.touch() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
  CREATE TRIGGER touch BEFORE INSERT ON app.items FOR EACH ROW EXECUTE FUNCTION app.touch();
  CREATE FUNCTION app.answer() RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 111 $$;
  CREATE VIEW app.visible AS SELECT id, code FROM app.items;
  CREATE SEQUENCE app.marker START 7;
`;
const row1 = `(1, 'a', 'calm', 1.250, '\\x00ff', '{"b":2,"a":1}', '[0:1]={4,5}', ROW('x', ARRAY[1,2]), '2026-01-02T03:04:05Z')`;
const row2 = `(2, 'b', NULL, NULL, NULL, NULL, NULL, NULL, NULL)`;
async function populated(reverse = false) {
  const owned = await database(fixture);
  await owned.db.query(`INSERT INTO app.items VALUES ${reverse ? row2 + ',' + row1 : row1 + ',' + row2}`);
  return owned;
}
async function withRole(owned: OwnedDatabase, run: (role: string) => Promise<void>) {
  const role = 'interleave_identity_' + randomBytes(8).toString('hex');
  const admin = new Client({ connectionString: adminUrl }); await admin.connect();
  try { await admin.query(`CREATE ROLE ${escapeIdentifier(role)}`); await run(role); }
  finally { await owned.close(); await admin.query(`DROP ROLE IF EXISTS ${escapeIdentifier(role)}`); await admin.end(); }
}
async function queryAsRole(owned: OwnedDatabase, role: string, sql: string) {
  await owned.db.query(`SET ROLE ${escapeIdentifier(role)}`);
  try { return await owned.db.query(sql); }
  finally { await owned.db.query('RESET ROLE'); }
}
async function queryFromUrl(url: string, sql: string) {
  const client = new Client({ connectionString: url }); await client.connect();
  try { return await client.query(sql); } finally { await client.end(); }
}

integration('fixture identity integration with real PostgreSQL', () => {
  afterAll(async () => { for (const owned of databases) await owned.close(); });
  test('fresh database names, allocation OIDs and row insertion order do not change the fixture identity', async () => {
    const first = await populated();
    const churn = await database('CREATE TABLE allocation_churn (id integer); DROP TABLE allocation_churn');
    await churn.close();
    const second = await populated(true);
    const a = await captureFixtureIdentity(first.connectionString); const b = await captureFixtureIdentity(second.connectionString);
    expect(first.name).not.toBe(second.name); expect(a.fingerprint).toBe(b.fingerprint);
    expect(a.components).toEqual(b.components); expect(a.counts.rows).toBe(2);
    expect(a.fingerprint).toMatch(/^[a-f0-9]{64}$/);
  });
  test('initial rows and array bounds affect data identity without changing schema identity', async () => {
    const owned = await populated(); const before = await captureFixtureIdentity(owned.connectionString);
    await owned.db.query("UPDATE app.items SET tags = '[1:2]={4,5}' WHERE id=1");
    const after = await captureFixtureIdentity(owned.connectionString);
    expect(after.components.data).not.toBe(before.components.data);
    expect(after.components.schema).toBe(before.components.schema);
  });
  test('table definitions, view definitions, functions, triggers and enum definitions affect schema identity', async () => {
    const owned = await populated(); let previous = await captureFixtureIdentity(owned.connectionString);
    for (const change of [
      'ALTER TABLE app.items ADD COLUMN extra integer DEFAULT 7',
      'CREATE OR REPLACE VIEW app.visible AS SELECT id, code FROM app.items WHERE id>1',
      'CREATE OR REPLACE FUNCTION app.answer() RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 999 $$',
      'ALTER TABLE app.items DISABLE TRIGGER touch',
      "ALTER TYPE app.mood ADD VALUE 'asleep'",
    ]) {
      await owned.db.query(change); const next = await captureFixtureIdentity(owned.connectionString);
      expect(next.components.schema, change).not.toBe(previous.components.schema); previous = next;
    }
  });
  test('sequence last_value, is_called and definition changes affect sequence identity', async () => {
    const owned = await database(fixture); const start = await captureFixtureIdentity(owned.connectionString);
    await owned.db.query("SELECT setval('app.marker',7,true)"); const called = await captureFixtureIdentity(owned.connectionString);
    await owned.db.query("SELECT setval('app.marker',9,true)"); const advanced = await captureFixtureIdentity(owned.connectionString);
    await owned.db.query('ALTER SEQUENCE app.marker INCREMENT BY 2'); const altered = await captureFixtureIdentity(owned.connectionString);
    expect(called.components.sequences).not.toBe(start.components.sequences);
    expect(advanced.components.sequences).not.toBe(called.components.sequences);
    expect(altered.components.sequences).not.toBe(advanced.components.sequences);
  });
  test('database defaults and effective connection settings affect settings identity', async () => {
    const owned = await database(fixture); const before = await captureFixtureIdentity(owned.connectionString);
    await owned.db.query(`ALTER DATABASE "${owned.name}" SET timezone = 'Asia/Kolkata'`);
    const after = await captureFixtureIdentity(owned.connectionString);
    expect(after.components.settings).not.toBe(before.components.settings);
    expect(after.components.data).toBe(before.components.data);
    const configured = new URL(owned.connectionString); configured.searchParams.set('options', '-c default_transaction_isolation=serializable');
    expect((await captureFixtureIdentity(configured.toString())).components.settings).not.toBe(after.components.settings);
  });
  test('attributes of a function owner affect environment identity without depending on unrelated cluster roles', async () => {
    const owned = await database(fixture); const role = 'interleave_role_' + randomBytes(8).toString('hex');
    const cleanup = new Client({ connectionString: adminUrl }); await cleanup.connect();
    try {
      await owned.db.query(`CREATE ROLE "${role}"; ALTER FUNCTION app.answer() OWNER TO "${role}"`);
      const before = await captureFixtureIdentity(owned.connectionString);
      await owned.db.query(`ALTER ROLE "${role}" BYPASSRLS`);
      const after = await captureFixtureIdentity(owned.connectionString);
      expect(after.components.settings).not.toBe(before.components.settings);
    } finally {
      await owned.close(); await cleanup.query(`DROP ROLE IF EXISTS "${role}"`); await cleanup.end();
    }
  });
  test('row, object and byte budgets fail explicitly instead of hashing a truncated fixture', async () => {
    const owned = await populated();
    for (const options of [{ maxRows: 1 }, { maxObjects: 1 }, { maxBytes: 64 }]) {
      await expect(captureFixtureIdentity(owned.connectionString, options)).rejects.toMatchObject({ code: 'budget-exceeded' });
    }
  });
  test('a total deadline or prior cancellation fails explicitly', async () => {
    const owned = await populated();
    await expect(captureFixtureIdentity(owned.connectionString, { timeoutMs: 1 })).rejects.toMatchObject({ code: 'budget-exceeded' });
    const controller = new AbortController(); controller.abort();
    await expect(captureFixtureIdentity(owned.connectionString, { signal: controller.signal })).rejects.toMatchObject({ code: 'aborted' });
  });
  test('rejects uncommitted setup and uncovered custom range types explicitly', async () => {
    const owned = await database(fixture); await owned.db.query('BEGIN');
    try { await expect(captureFixtureIdentity(owned.connectionString)).rejects.toMatchObject({ code: 'not-quiescent' }); }
    finally { await owned.db.query('ROLLBACK'); }
    await owned.db.query('CREATE TYPE app.span AS RANGE (subtype=integer)');
    await expect(captureFixtureIdentity(owned.connectionString)).rejects.toMatchObject({ code: 'unsupported' });
  });
  test('temporary fixture state and custom text-search objects fail closed instead of being omitted', async () => {
    const owned = await database('CREATE SCHEMA app');
    await owned.db.query('CREATE TEMP TABLE hidden_fixture(value integer)');
    await expect(captureFixtureIdentity(owned.connectionString)).rejects.toMatchObject({ code: 'unsupported' });
    await owned.db.query('DROP TABLE hidden_fixture');
    await owned.db.query('CREATE TEXT SEARCH DICTIONARY app.words (TEMPLATE=pg_catalog.simple)');
    await expect(captureFixtureIdentity(owned.connectionString)).rejects.toMatchObject({ code: 'unsupported' });
  });
  test('row multiplicity, materialized view contents and partition leaf data are captured', async () => {
    const owned = await database('CREATE TABLE base(value integer); INSERT INTO base VALUES(1); CREATE MATERIALIZED VIEW cached AS SELECT * FROM base; CREATE TABLE partitioned(value integer) PARTITION BY RANGE(value); CREATE TABLE leaf PARTITION OF partitioned FOR VALUES FROM(0) TO(10); INSERT INTO partitioned VALUES(3)');
    const first = await captureFixtureIdentity(owned.connectionString); expect(first.counts.rows).toBe(3);
    await owned.db.query('INSERT INTO base VALUES(1)'); const duplicate = await captureFixtureIdentity(owned.connectionString);
    expect(duplicate.components.data).not.toBe(first.components.data); expect(duplicate.counts.rows).toBe(4);
    await owned.db.query('REFRESH MATERIALIZED VIEW cached'); const refreshed = await captureFixtureIdentity(owned.connectionString);
    expect(refreshed.components.data).not.toBe(duplicate.components.data); expect(refreshed.counts.rows).toBe(5);
  });
  test('returns only digests and coverage metadata, never raw fixture row values or function bodies', async () => {
    const owned = await database("CREATE TABLE secret_values(value text); INSERT INTO secret_values VALUES ('private-fixture-value')");
    const identity = await captureFixtureIdentity(owned.connectionString);
    expect(JSON.stringify(identity)).not.toContain('private-fixture-value');
    expect(new FixtureIdentityError('unsupported', 'test')).toBeInstanceOf(Error);
  });
  test('default function privileges differ from an explicitly empty ACL', async () => {
    const owned = await database('CREATE FUNCTION public.answer() RETURNS integer LANGUAGE sql AS $$ SELECT 42 $$');
    await withRole(owned, async role => {
      const before = await captureFixtureIdentity(owned.connectionString);
      expect((await queryAsRole(owned, role, 'SELECT public.answer()')).rows).toEqual([{ answer: 42 }]);
      await owned.db.query('REVOKE ALL ON FUNCTION public.answer() FROM PUBLIC, postgres');
      const after = await captureFixtureIdentity(owned.connectionString);
      await expect(queryAsRole(owned, role, 'SELECT public.answer()')).rejects.toMatchObject({ code: '42501' });
      expect(after.components.schema).not.toBe(before.components.schema);
    });
  });
  test('recreated named owners and default ACLs remain stable across fresh role OIDs', async () => {
    const role='interleave_owner_' + randomBytes(8).toString('hex');
    const admin=new Client({ connectionString: adminUrl }); await admin.connect();
    const first=await database(); const second=await database();
    const setup = async (owned: OwnedDatabase) => {
      await admin.query(`CREATE ROLE ${escapeIdentifier(role)}`);
      await owned.db.query(`CREATE FUNCTION answer() RETURNS integer LANGUAGE sql AS $$ SELECT 42 $$; ALTER FUNCTION answer() OWNER TO ${escapeIdentifier(role)}`);
      return (await admin.query<{ oid: number }>('SELECT oid FROM pg_roles WHERE rolname=$1',[role])).rows[0]!.oid;
    };
    try {
      const firstOid=await setup(first); const before=await captureFixtureIdentity(first.connectionString);
      await first.close(); await admin.query(`DROP ROLE ${escapeIdentifier(role)}`);
      const secondOid=await setup(second); const after=await captureFixtureIdentity(second.connectionString);
      expect(secondOid).not.toBe(firstOid); expect(after.fingerprint).toBe(before.fingerprint);
    } finally { await first.close(); await second.close(); await admin.query(`DROP ROLE IF EXISTS ${escapeIdentifier(role)}`); await admin.end(); }
  });
  test('internal foreign-key trigger modes change identity without including generated trigger OIDs', async () => {
    const sql = 'CREATE TABLE parent(id int PRIMARY KEY); CREATE TABLE child(parent_id int REFERENCES parent(id))';
    const first = await database(sql); const second = await database(sql);
    const before = await captureFixtureIdentity(first.connectionString);
    expect((await captureFixtureIdentity(second.connectionString)).fingerprint).toBe(before.fingerprint);
    await expect(first.db.query('INSERT INTO child VALUES (42)')).rejects.toMatchObject({ code: '23503' });
    await first.db.query('ALTER TABLE child DISABLE TRIGGER ALL');
    const disabled = await captureFixtureIdentity(first.connectionString);
    await first.db.query('INSERT INTO child VALUES (42)');
    expect(disabled.components.schema).not.toBe(before.components.schema);
  });
  test('effective tenant context supplied through startup options changes identity and actor results', async () => {
    const owned = await database("CREATE TABLE tenants(id text); INSERT INTO tenants VALUES ('first'),('second'); CREATE VIEW visible_tenant AS SELECT id FROM tenants WHERE id=current_setting('app.tenant_id')");
    const first = new URL(owned.connectionString); first.searchParams.set('options', '-c app.tenant_id=first');
    const second = new URL(owned.connectionString); second.searchParams.set('options', '--app.tenant_id=second');
    const a = await captureFixtureIdentity(first.toString()); const b = await captureFixtureIdentity(second.toString());
    expect((await queryFromUrl(first.toString(), 'SELECT * FROM visible_tenant')).rows).toEqual([{ id: 'first' }]);
    expect((await queryFromUrl(second.toString(), 'SELECT * FROM visible_tenant')).rows).toEqual([{ id: 'second' }]);
    expect(a.components.settings).not.toBe(b.components.settings);
    expect(a.components.schema).toBe(b.components.schema); expect(a.components.data).toBe(b.components.data);
    expect(JSON.stringify(a)).not.toContain('app.tenant_id');
  });
  test('effective custom database defaults change identity before actors connect', async () => {
    const owned = await database("CREATE VIEW tenant_context AS SELECT current_setting('app.tenant_id') AS tenant");
    await owned.db.query(`ALTER DATABASE ${escapeIdentifier(owned.name)} SET app.tenant_id='first'`);
    const first = await captureFixtureIdentity(owned.connectionString);
    expect((await queryFromUrl(owned.connectionString, 'SELECT * FROM tenant_context')).rows).toEqual([{ tenant: 'first' }]);
    await owned.db.query(`ALTER DATABASE ${escapeIdentifier(owned.name)} SET app.tenant_id='second'`);
    const second = await captureFixtureIdentity(owned.connectionString);
    expect((await queryFromUrl(owned.connectionString, 'SELECT * FROM tenant_context')).rows).toEqual([{ tenant: 'second' }]);
    expect(second.components.settings).not.toBe(first.components.settings);
  });
  test('startup spellings and escaped values retain custom setting identity without Unicode folding collisions', async () => {
    const owned=await database();
    const capture = async (options: string) => { const url=new URL(owned.connectionString); url.searchParams.set('options',options); return captureFixtureIdentity(url.toString()); };
    const first=await capture('-e -c app.tenant_id=hello\\ world');
    const attached=await capture('-ecAPP.tenant-id=hello\\ world');
    const long=await capture('-e --app.tenant_id=hello\\ world');
    expect(attached.fingerprint).toBe(first.fingerprint); expect(long.fingerprint).toBe(first.fingerprint);
    const upper=await capture('-c app.Ä=first -c app.ä=second');
    const lower=await capture('-c app.Ä=first -c app.ä=third');
    expect(upper.components.settings).not.toBe(lower.components.settings);
    expect(JSON.stringify(first)).not.toContain('hello');
  });
  test('session-role database defaults use effective precedence even under another current role', async () => {
    const owned=await database();
    await withRole(owned, async role => {
      await owned.db.query(`ALTER DATABASE ${escapeIdentifier(owned.name)} SET app.tenant_id='database'`);
      await owned.db.query(`ALTER ROLE postgres IN DATABASE ${escapeIdentifier(owned.name)} SET app.tenant_id='login-role'`);
      // SET ROLE is a startup setting; PostgreSQL still applies the login role's defaults.
      await owned.db.query(`GRANT pg_read_all_stats TO ${escapeIdentifier(role)}`);
      const url=new URL(owned.connectionString); url.searchParams.set('options',`-c role=${role}`);
      const first=await captureFixtureIdentity(url.toString());
      expect((await queryFromUrl(url.toString(), "SELECT current_setting('app.tenant_id') AS tenant")).rows).toEqual([{ tenant: 'login-role' }]);
      await owned.db.query(`ALTER ROLE postgres IN DATABASE ${escapeIdentifier(owned.name)} SET app.tenant_id='changed-login-role'`);
      const second=await captureFixtureIdentity(url.toString());
      expect(second.components.settings).not.toBe(first.components.settings);
      url.searchParams.set('options',`-c role=${role} -c app.tenant_id=overridden`);
      const overridden=await captureFixtureIdentity(url.toString());
      await owned.db.query(`ALTER ROLE postgres IN DATABASE ${escapeIdentifier(owned.name)} SET app.tenant_id='hidden-default-change'`);
      const unchanged=await captureFixtureIdentity(url.toString());
      expect(unchanged.components.settings).toBe(overridden.components.settings);
    });
  });
  test('planner settings that change row selection affect identity', async () => {
    const owned = await database('CREATE TABLE choices(id int); INSERT INTO choices VALUES(2),(1); CREATE INDEX choices_id ON choices(id)');
    const on = new URL(owned.connectionString); on.searchParams.set('options', '-c enable_seqscan=on');
    const off = new URL(owned.connectionString); off.searchParams.set('options', '-c enable_seqscan=off');
    const a=await captureFixtureIdentity(on.toString()); const b=await captureFixtureIdentity(off.toString());
    expect((await queryFromUrl(on.toString(), 'SELECT id FROM choices WHERE id>0 LIMIT 1')).rows).toEqual([{ id: 2 }]);
    expect((await queryFromUrl(off.toString(), 'SELECT id FROM choices WHERE id>0 LIMIT 1')).rows).toEqual([{ id: 1 }]);
    expect(a.components.settings).not.toBe(b.components.settings);
  });
  test('captures application name and custom PGOPTIONS from the actual actor startup defaults', async () => {
    const owned=await database();
    const priorOptions=process.env.PGOPTIONS; const priorName=process.env.PGAPPNAME;
    try {
      process.env.PGOPTIONS='-c app.tenant_id=first'; process.env.PGAPPNAME='first-actor';
      const first=await captureFixtureIdentity(owned.connectionString);
      expect((await queryFromUrl(owned.connectionString, "SELECT current_setting('application_name') AS name,current_setting('app.tenant_id') AS tenant")).rows).toEqual([{ name: 'first-actor', tenant: 'first' }]);
      process.env.PGOPTIONS='-c app.tenant_id=second';
      const tenantChanged=await captureFixtureIdentity(owned.connectionString);
      expect(tenantChanged.components.settings).not.toBe(first.components.settings);
      process.env.PGAPPNAME='second-actor';
      const nameChanged=await captureFixtureIdentity(owned.connectionString);
      expect(nameChanged.components.settings).not.toBe(tenantChanged.components.settings);
      const url=new URL(owned.connectionString); url.searchParams.set('options','-c app.tenant_id=from-url'); url.searchParams.set('application_name','url-actor');
      const overridden=await captureFixtureIdentity(url.toString());
      process.env.PGOPTIONS='-c app.tenant_id=hidden'; process.env.PGAPPNAME='hidden-actor';
      expect((await captureFixtureIdentity(url.toString())).fingerprint).toBe(overridden.fingerprint);
    } finally {
      if (priorOptions === undefined) delete process.env.PGOPTIONS; else process.env.PGOPTIONS=priorOptions;
      if (priorName === undefined) delete process.env.PGAPPNAME; else process.env.PGAPPNAME=priorName;
    }
  });
  test('standalone domain collation changes comparison behavior and identity', async () => {
    const owned = await database('CREATE DOMAIN label AS text COLLATE "C"');
    const before=await captureFixtureIdentity(owned.connectionString);
    expect((await owned.db.query("SELECT 'a'::label < 'B'::label AS ordered")).rows).toEqual([{ ordered: false }]);
    await owned.db.query('DROP DOMAIN label; CREATE DOMAIN label AS text COLLATE "en-x-icu"');
    const after=await captureFixtureIdentity(owned.connectionString);
    expect((await owned.db.query("SELECT 'a'::label < 'B'::label AS ordered")).rows).toEqual([{ ordered: true }]);
    expect(after.components.schema).not.toBe(before.components.schema);
  });
  test('baseline PL/pgSQL usage privileges affect identity and anonymous block execution', async () => {
    const owned=await database();
    await withRole(owned, async role => {
      const before=await captureFixtureIdentity(owned.connectionString);
      expect((await queryAsRole(owned, role, 'DO $$ BEGIN NULL; END $$ LANGUAGE plpgsql')).command).toBe('DO');
      await owned.db.query('REVOKE USAGE ON LANGUAGE plpgsql FROM PUBLIC');
      const after=await captureFixtureIdentity(owned.connectionString);
      await expect(queryAsRole(owned, role, 'DO $$ BEGIN NULL; END $$ LANGUAGE plpgsql')).rejects.toMatchObject({ code: '42501' });
      expect(after.components.schema).not.toBe(before.components.schema);
    });
  });
  test.each([
    {
      label: 'function in pg_catalog',
      setup: `CREATE FUNCTION pg_catalog.interleave_hidden_function()
        RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 42 $$`,
      query: 'SELECT pg_catalog.interleave_hidden_function() AS value',
      rows: [{ value: 42 }],
    },
    {
      label: 'relation in information_schema',
      setup: `CREATE TABLE information_schema.interleave_hidden_relation(value integer);
        INSERT INTO information_schema.interleave_hidden_relation VALUES (42)`,
      query: 'SELECT value FROM information_schema.interleave_hidden_relation',
      rows: [{ value: 42 }],
    },
    {
      label: 'new pg_-prefixed schema',
      setup: `SET allow_system_table_mods=on;
        CREATE SCHEMA pg_interleave_hidden;
        CREATE TABLE pg_interleave_hidden.value(value integer);
        INSERT INTO pg_interleave_hidden.value VALUES (42);
        RESET allow_system_table_mods`,
      query: 'SELECT value FROM pg_interleave_hidden.value',
      rows: [{ value: 42 }],
    },
  ])('fails closed on a user-created $label', async ({ setup, query, rows }) => {
    const owned = await database(setup);
    expect((await owned.db.query(query)).rows).toEqual(rows);
    await expect(captureFixtureIdentity(owned.connectionString)).rejects.toMatchObject({ code: 'unsupported' });
  });
  test('canonical byte limits include retained row digests and aggregate hash inputs', async () => {
    const owned = await database(`CREATE TABLE empty_rows ();
      INSERT INTO empty_rows SELECT FROM generate_series(1, 10000)`);
    await expect(captureFixtureIdentity(owned.connectionString, { maxBytes: 100_000 }))
      .rejects.toMatchObject({ code: 'budget-exceeded' });
    const identity = await captureFixtureIdentity(owned.connectionString);
    expect(identity.counts.rows).toBe(10_000);
    expect(identity.counts.bytes).toBeGreaterThan(100_000);
  });
  test('early unsupported guards do not execute custom search-path operators', async () => {
    const owned = await database(`CREATE SCHEMA app;
      CREATE TABLE app.capture_side_effect(value integer);
      CREATE FUNCTION app.unsafe_oid_equal(oid,oid) RETURNS boolean LANGUAGE plpgsql AS $$
      BEGIN
        INSERT INTO app.capture_side_effect VALUES (1);
        RETURN $1 OPERATOR(pg_catalog.=) $2;
      END $$;
      CREATE OPERATOR app.= (LEFTARG=oid, RIGHTARG=oid, FUNCTION=app.unsafe_oid_equal)`);
    const configured = new URL(owned.connectionString);
    configured.searchParams.set('options', '-c search_path=app,pg_catalog');
    await expect(captureFixtureIdentity(configured.toString())).rejects.toMatchObject({ code: 'unsupported' });
    expect((await owned.db.query('SELECT count(*)::int AS count FROM app.capture_side_effect')).rows)
      .toEqual([{ count: 0 }]);
  });
  test('rejects custom serialization casts before evaluating any catalog record', async () => {
    const owned=await database(`CREATE TABLE capture_side_effect(value integer);
      CREATE FUNCTION unsafe_catalog_output(jsonb) RETURNS text LANGUAGE plpgsql AS $$
      BEGIN INSERT INTO capture_side_effect VALUES (1); RETURN 'masked'; END $$;
      CREATE CAST (jsonb AS text) WITH FUNCTION unsafe_catalog_output(jsonb)`);
    await expect(captureFixtureIdentity(owned.connectionString)).rejects.toMatchObject({ code: 'unsupported' });
    expect((await owned.db.query('SELECT count(*)::int AS count FROM capture_side_effect')).rows).toEqual([{ count: 0 }]);
  });
});
