import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import type { ActorContext, ActorResult, Scenario } from '@pavangupta352/interleave';
import type { PrismaClient } from './generated/prisma/client.ts';
import { checkout } from './src/checkout.ts';
import { withPrisma, type ClientOptions } from './src/db.ts';
import { orderLifecycle, type OrderLifecycleResult } from './src/orders.ts';
import { compareAndSet, conditionalDecrement, readThenWrite, serializable, type PurchaseResult } from './src/purchases.ts';

export type Behavior = 'checkout' | 'read-then-write' | 'compare-and-set' | 'conditional-decrement'
  | 'serializable-retry' | 'serializable-no-retry' | 'order-lifecycle';

const PRODUCT = 1;
const INITIAL_STOCK = 1;
// Generated by the pinned Prisma CLI from prisma/schema.prisma. Record with
// `--include prisma` so the schema and this migration are part of the identity.
const migration = new URL('./prisma/migrations/0_init/migration.sql', import.meta.url);

type Operation = (prisma: PrismaClient, productId: number, buyer: string) => Promise<PurchaseResult | OrderLifecycleResult>;

function operationFor(behavior: Behavior): Operation {
  switch (behavior) {
    case 'checkout': return checkout;
    case 'read-then-write': return readThenWrite;
    case 'compare-and-set': return compareAndSet;
    case 'conditional-decrement': return conditionalDecrement;
    case 'serializable-retry': return (prisma: PrismaClient, id: number, buyer: string) => serializable(prisma, id, buyer, true);
    case 'serializable-no-retry': return (prisma: PrismaClient, id: number, buyer: string) => serializable(prisma, id, buyer, false);
    case 'order-lifecycle': return orderLifecycle;
    default: throw new TypeError(`Unknown behavior: ${String(behavior)}`);
  }
}

const fulfilled = <T>(results: ActorResult[]) => results.map(result => result.value as T);

/**
 * Two buyers, alice and bob, each try to buy the last desk lamp. `checkout`
 * (the default) runs src/checkout.ts, the operation under test.
 */
export function createCheckoutScenario(behavior: Behavior = 'checkout', options: ClientOptions = {}): Scenario {
  const operation = operationFor(behavior);
  const actor = (context: ActorContext) => withPrisma(context, prisma => operation(prisma, PRODUCT, context.actor), options);
  return {
    name: `prisma-${behavior}`,
    async setup({ db }) {
      await db.query(await readFile(migration, 'utf8'));
      await db.query('INSERT INTO products (id, name, stock) VALUES ($1, $2, $3)', [PRODUCT, 'Desk lamp', INITIAL_STOCK]);
    },
    actors: { alice: actor, bob: actor },
    async invariant({ db, results }) {
      if (behavior === 'order-lifecycle') {
        assert.deepEqual((await db.query('SELECT id FROM orders')).rows, [], 'Every order must be rolled back or deleted');
        for (const value of fulfilled<OrderLifecycleResult>(results)) {
          assert.deepEqual(value, { code: 'P2002', afterRollback: 0, created: 1, updated: 2, read: 2, deleted: 2 });
        }
        return;
      }
      const { rows: [product] } = await db.query('SELECT stock FROM products WHERE id = $1', [PRODUCT]);
      const { rows: [sold] } = await db.query('SELECT count(*)::int AS orders FROM orders WHERE product_id = $1', [PRODUCT]);
      assert.ok(sold.orders <= INITIAL_STOCK, 'Accepted orders exceed the available stock');
      assert.ok(product.stock + sold.orders === INITIAL_STOCK, 'Each accepted order must remove exactly one unit of stock');
      const ordered = fulfilled<PurchaseResult>(results).filter(value => value.status === 'ordered').length;
      assert.ok(ordered === sold.orders, 'Every reported order must be stored exactly once');
    },
  };
}

export default createCheckoutScenario();
