export interface SharedInstallerConfig {
  files: Array<{ path: string; bytes: number; sha256: string }>;
  archives: string[];
  sourceFingerprint: string;
  entry: string;
  includes: string[];
}

/** Generate a deterministic, dependency-free installer. The bundle verifier
 * authenticates this complete program before users execute it. */
export function sharedInstallerSource(config: SharedInstallerConfig): string {
  return `// Generated by Interleave. Verify this bundle before running the installer.\nconst config = ${JSON.stringify(config)};\n` + String.raw`
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { constants } from 'node:fs';
import { lstat, open, mkdir, mkdtemp, realpath, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const started = performance.now();
const deadlineMs = 120_000;
const outputLimit = 1024 * 1024;
let outputBytes = 0;
let cacheRoot;
let child;
let interrupted;
const observedDirectories = new Map();
const sameNode = (a, b) => a.dev === b.dev && a.ino === b.ino;
const errorText = error => error instanceof Error ? error.message : String(error);
function fail(message) { throw new Error(message); }
function checkTime() {
  if (interrupted) fail('Installation interrupted by ' + interrupted);
  if (performance.now() - started >= deadlineMs) fail('Installation exceeded its 120 second total time limit');
}
function portable(path, allowDot = false) {
  if (allowDot && path === '.') return path;
  if (typeof path !== 'string' || !path || Buffer.byteLength(path) > 4096 || /[\\:\x00-\x1f\x7f]/.test(path)) fail('Invalid portable bundle path');
  const parts = path.split('/');
  if (parts.some(part => !part || part === '.' || part === '..')) fail('Invalid portable bundle path: ' + path);
  return path;
}
function validateConfig() {
  if (!config || !Array.isArray(config.files) || !config.files.length || config.files.length > 10_000 ||
      !Array.isArray(config.archives) || !config.archives.length || config.archives.length > 10_000 ||
      !Array.isArray(config.includes) || config.includes.length > 10_000 ||
      !/^[a-f0-9]{64}$/.test(config.sourceFingerprint)) fail('Invalid installer configuration');
  const paths = new Set(); let bytes = 0;
  for (const file of config.files) {
    if (!file || typeof file !== 'object') fail('Invalid installer file record');
    portable(file.path);
    if (paths.has(file.path) || file.path.split('/').includes('node_modules') || ['app/.npmrc', 'app/npm-shrinkwrap.json'].includes(file.path) ||
        !Number.isSafeInteger(file.bytes) || file.bytes < 0 || file.bytes > 16 * 1024 * 1024 ||
        !/^[a-f0-9]{64}$/.test(file.sha256)) fail('Invalid installer file record: ' + file.path);
    paths.add(file.path); bytes += file.bytes;
  }
  if (bytes > 128 * 1024 * 1024) fail('Installer files exceed the total byte limit');
  const archives = new Set();
  for (const archive of config.archives) {
    portable(archive);
    if (!paths.has(archive) || archive.startsWith('app/') || archives.has(archive)) fail('Invalid installer archive path: ' + archive);
    archives.add(archive);
  }
  portable(config.entry);
  for (const include of config.includes) portable(include, true);
  for (const required of ['app/package.json', 'app/package-lock.json', 'app/' + config.entry]) {
    if (!paths.has(required)) fail('Installer is missing a required original file: ' + required);
  }
}
async function directory(path) {
  checkTime();
  const stat = await lstat(path);
  if (!stat.isDirectory() || stat.isSymbolicLink()) fail('Expected an ordinary directory: ' + path);
  const previous = observedDirectories.get(path);
  if (previous && !sameNode(previous, stat)) fail('Directory was replaced during installation: ' + path);
  observedDirectories.set(path, stat);
  return stat;
}
async function ordinaryPath(root, relative, isDirectory = false) {
  portable(relative);
  await directory(root);
  const parts = relative.split('/'); let path = root;
  for (const part of parts.slice(0, isDirectory ? undefined : -1)) {
    path = join(path, part); await directory(path);
  }
  return resolve(root, relative);
}
async function verifyFile(root, record) {
  checkTime();
  const path = await ordinaryPath(root, record.path);
  const before = await lstat(path);
  if (!before.isFile() || before.isSymbolicLink() || before.size !== record.bytes) fail('Bundled file is not an unchanged ordinary file: ' + record.path);
  const handle = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK);
  try {
    const opened = await handle.stat();
    if (!opened.isFile() || opened.size !== record.bytes || !sameNode(before, opened)) fail('Bundled file was replaced: ' + record.path);
    const data = Buffer.alloc(record.bytes); let offset = 0;
    while (offset < data.length) {
      checkTime();
      const { bytesRead } = await handle.read(data, offset, data.length - offset, offset);
      if (bytesRead === 0) break;
      offset += bytesRead;
    }
    const extra = await handle.read(Buffer.alloc(1), 0, 1, offset);
    const after = await handle.stat();
    const current = await lstat(path);
    if (offset !== record.bytes || extra.bytesRead !== 0 || !sameNode(opened, current) || !sameNode(opened, after) ||
        after.size !== record.bytes || opened.mtimeMs !== after.mtimeMs || opened.ctimeMs !== after.ctimeMs ||
        createHash('sha256').update(data).digest('hex') !== record.sha256) fail('Bundled file integrity mismatch: ' + record.path);
  } finally { await handle.close(); }
  await ordinaryPath(root, record.path);
}
async function absent(path, reason) {
  try { await lstat(path); }
  catch (error) { if (error.code === 'ENOENT') return; throw error; }
  fail(reason + ': ' + path);
}
async function stableDirectories() {
  for (const path of observedDirectories.keys()) await directory(path);
}
function stopChild() {
  // A process that has exited may still have descendants holding its pipes.
  if (!child || !Number.isSafeInteger(child.pid) || child.pid <= 0) return;
  try { process.kill(-child.pid, 'SIGKILL'); }
  catch { try { child.kill('SIGKILL'); } catch {} }
}
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => { interrupted = signal; stopChild(); });
async function run(executable, args, cwd, env) {
  checkTime(); await stableDirectories();
  const output = await new Promise((fulfill, reject) => {
    let output = ''; let failure;
    child = spawn(executable, args, { cwd, env, shell: false, detached: true, stdio: ['ignore', 'pipe', 'pipe'] });
    const current = child;
    const timeout = setTimeout(() => {
      failure = new Error('Installation exceeded its 120 second total time limit'); stopChild();
    }, Math.max(1, deadlineMs - (performance.now() - started)));
    const capture = data => {
      outputBytes += data.length;
      if (outputBytes > outputLimit) { failure = new Error('Installation exceeded its 1 MiB subprocess output limit'); stopChild(); return; }
      output = (output + data.toString('utf8')).slice(-16_384);
    };
    current.stdout.on('data', capture); current.stderr.on('data', capture);
    current.once('error', error => { failure = error; });
    current.once('close', (code, signal) => {
      clearTimeout(timeout); if (child === current) child = undefined;
      if (failure) reject(failure);
      else if (interrupted) reject(new Error('Installation interrupted by ' + interrupted));
      else if (code !== 0) reject(new Error(executable + ' failed (' + (signal || code) + '):\n' + output));
      else fulfill(output);
    });
  });
  checkTime(); await stableDirectories();
  return output;
}

try {
  validateConfig();
  if (process.platform === 'win32') fail('The shared installer currently requires a POSIX Node/npm installation');
  const requestedRoot = dirname(fileURLToPath(import.meta.url));
  await directory(requestedRoot);
  const root = await realpath(requestedRoot);
  if (root !== requestedRoot) fail('The bundle directory must not resolve through a symbolic link');
  const app = await ordinaryPath(root, 'app', true);
  await absent(join(app, '.npmrc'), 'Application .npmrc is unsupported by the fixed install profile');
  await absent(join(app, 'npm-shrinkwrap.json'), 'Application npm-shrinkwrap.json is unsupported by the fixed install profile');
  await absent(join(app, 'node_modules'), 'A clean install requires app/node_modules to be absent; preserve or remove it explicitly before retrying');
  for (const record of config.files) await verifyFile(root, record);

  cacheRoot = await mkdtemp(join(root, '.interleave-install-'));
  await directory(cacheRoot);
  const cache = join(cacheRoot, 'cache'); const home = join(cacheRoot, 'home');
  await mkdir(cache); await mkdir(home); await directory(cache); await directory(home);
  const userConfig = join(cacheRoot, 'user.npmrc'); const globalConfig = join(cacheRoot, 'global.npmrc');
  await writeFile(userConfig, '', { flag: 'wx', mode: 0o600 });
  await writeFile(globalConfig, '', { flag: 'wx', mode: 0o600 });
  const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => !/^(?:npm_|node_)/i.test(key) && key !== 'INIT_CWD'));
  env.HOME = home; env.USERPROFILE = home; env.XDG_CONFIG_HOME = home;
  const options = [
    '--cache', cache, '--userconfig', userConfig, '--globalconfig', globalConfig,
    '--offline', '--ignore-scripts=true', '--audit=false', '--fund=false', '--progress=false',
    '--update-notifier=false', '--global=false', '--include=dev', '--include=optional', '--include=peer',
    '--install-strategy=hoisted', '--legacy-peer-deps=false', '--install-links=true', '--bin-links=true',
    '--package-lock=true', '--workspaces=false',
  ];
  for (const archive of config.archives) {
    await verifyFile(root, config.files.find(file => file.path === archive));
    await run('npm', ['cache', 'add', resolve(root, archive), '--prefix', cacheRoot, ...options], cacheRoot, env);
  }
  await absent(join(app, '.npmrc'), 'Application .npmrc appeared during installation');
  await absent(join(app, 'npm-shrinkwrap.json'), 'Application npm-shrinkwrap.json appeared during installation');
  await absent(join(app, 'node_modules'), 'Application node_modules appeared during installation; preserving it');
  for (const record of config.files) if (record.path.startsWith('app/')) await verifyFile(root, record);
  await run('npm', ['ci', '--prefix', app, ...options], cacheRoot, env);
  for (const record of config.files) await verifyFile(root, record);
  await absent(join(app, '.npmrc'), 'Application .npmrc appeared during installation');
  await absent(join(app, 'npm-shrinkwrap.json'), 'Application npm-shrinkwrap.json appeared during installation');

  const runtime = await ordinaryPath(root, 'app/node_modules/@pavangupta352/interleave', true);
  const identityModule = await ordinaryPath(root, 'app/node_modules/@pavangupta352/interleave/dist/source-identity.js');
  const identityStat = await lstat(identityModule);
  if (!identityStat.isFile() || identityStat.isSymbolicLink()) fail('Installed source-identity.js is not an ordinary file');
  const capture = [
    "import { pathToFileURL } from 'node:url';",
    'const { captureExportSourceIdentity } = await import(pathToFileURL(process.argv[1]).href);',
    'const identity = await captureExportSourceIdentity(process.argv[2], JSON.parse(process.argv[3]), process.argv[4]);',
    "if (!identity || identity.fingerprint !== process.argv[5]) throw new Error('Installed source identity fingerprint does not match the original recording; no scenario was imported');",
  ].join('\n');
  await run(process.execPath, ['--input-type=module', '--eval', capture, identityModule, resolve(app, config.entry),
    JSON.stringify({ projectRoot: app, include: config.includes, timeoutMs: Math.max(1, Math.min(120_000, Math.floor(deadlineMs - (performance.now() - started)))) }),
    runtime, config.sourceFingerprint], cacheRoot, env);
  for (const record of config.files) await verifyFile(root, record);
  console.log('Offline installation complete. The original source and complete installed identity match; no scenario was imported.');
} catch (error) {
  stopChild(); process.exitCode = 1;
  console.error('Interleave installation failed: ' + errorText(error));
} finally {
  // Never recursively delete a path that another process could have replaced.
  // The unique cache contains no durable bundle inputs and can be removed after inspection.
  if (cacheRoot) {
    const current = await lstat(cacheRoot).catch(() => undefined);
    const previous = observedDirectories.get(cacheRoot);
    const owned = current && previous && current.isDirectory() && !current.isSymbolicLink() && sameNode(current, previous);
    console.error(owned
      ? 'Installer cache retained for inspection; remove this exact directory when finished: ' + cacheRoot
      : previous
        ? 'Installer cache ownership changed; nothing was removed. Inspect this path and any moved cache manually: ' + cacheRoot
        : 'Installer cache ownership was not recorded; nothing was removed. Inspect this path manually: ' + cacheRoot);
  }
}
`;
}
